create table usuario (
	id bigint generated by default as identity,  
	account_expired boolean not null, 
	account_locked boolean not null, 
	active boolean not null, 
	credentials_expired boolean not null, 
	email varchar(255), 
	password varchar(255), 
	roles varchar(255), 
	username varchar(255), 
	nome varchar(255), 
	primary key (id)
);
alter table usuario add constraint UK_692bsnqxa8m9fmx7m1yc6hsui unique (email);