create table cliente (
	id bigint generated by default as identity, 
	cpf varchar(14) NOT NULL, 
	uuid UUID not null,
	data_nascimento date, 
	nome varchar(255), 
	status BOOLEAN,
	primary key (id)
);
CREATE UNIQUE INDEX idx_unique_cpf ON cliente (cpf);

create table conta (
	id bigint generated by default as identity, 
	saldo numeric(19,2), 
	cliente_id bigint, 
	primary key (id)
);

create table usuario (id bigint generated by default as identity, nome varchar(255), account_expired boolean not null, account_locked boolean not null, active boolean not null, cpf varchar(255), credentials_expired boolean not null, email varchar(255), password varchar(255), roles varchar(255), telefone varchar(255), username varchar(255), primary key (id));
alter table usuario add constraint UK_692bsnqxa8m9fmx7m1yc6hsui unique (cpf);

alter table conta add constraint FKfksaesgpmec0cph81iq5or1wn foreign key (cliente_id) references cliente